# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-03 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timeline', '0003_auto_20170602_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
    ]
