# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-16 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timeline', '0006_auto_20170615_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='extension_id',
            field=models.IntegerField(default=-1, help_text='如评论ID有效', verbose_name='扩展ID'),
        ),
        migrations.AddField(
            model_name='timeline',
            name='motion',
            field=models.CharField(blank=True, default=None, help_text='创建 修改 分享时才有用', max_length=500, null=True, verbose_name='动态发表心情'),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='type',
            field=models.IntegerField(choices=[(0, '创建作品'), (1, '修改作品'), (2, '分享作品'), (3, '点赞作品'), (4, '评论作品'), (5, '审核作品'), (6, '认领作品')], verbose_name='时间线内容类型'),
        ),
    ]
