# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-25 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timeline', '0007_auto_20170616_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='type',
            field=models.IntegerField(choices=[(0, '发表'), (1, '修订'), (2, '分享'), (3, '点赞'), (4, '评论'), (5, '审核'), (6, '认领')], verbose_name='时间线内容类型'),
        ),
    ]
