# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-12 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractUser',
            fields=[
                ('uid', models.AutoField(auto_created=True, db_index=True, editable=False, primary_key=True, serialize=False, verbose_name='用户编号')),
                ('nickname', models.CharField(default=None, max_length=20, verbose_name='笔名/称呼')),
                ('username', models.CharField(default=None, max_length=20, verbose_name='用户账号')),
                ('password', models.CharField(blank=True, default=None, max_length=40, verbose_name='用户密码')),
                ('pwd_login', models.BooleanField(default=True, verbose_name='是否需要密码登录')),
                ('last_login', models.DateTimeField(default=None, verbose_name='上次登录时间')),
                ('last_ipv4', models.GenericIPAddressField(default=None, verbose_name='上次登录IP')),
                ('phone', models.CharField(default=None, max_length=20, verbose_name='联系方式')),
                ('email', models.EmailField(default=None, max_length=40, verbose_name='电子邮箱')),
                ('avatar', models.CharField(default=None, max_length=32, verbose_name='头像地址')),
            ],
        ),
    ]
