# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-15 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AbstractUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractuser',
            name='is_frozen',
            field=models.BooleanField(default=False, verbose_name='是否被冻结'),
        ),
        migrations.AlterField(
            model_name='abstractuser',
            name='nickname',
            field=models.CharField(default=None, max_length=20, null=True, unique=True, verbose_name='笔名/称呼'),
        ),
    ]
