# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-15 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AbstractUser', '0002_auto_20170115_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractuser',
            name='this_ipv4',
            field=models.GenericIPAddressField(default=None, null=True, verbose_name='本次登录IP'),
        ),
        migrations.AddField(
            model_name='abstractuser',
            name='this_login',
            field=models.DateTimeField(default=None, null=True, verbose_name='本次登录时间'),
        ),
    ]
