# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-21 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AbstractUser', '0004_abstractuser_login_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractuser',
            name='username',
            field=models.CharField(default=None, max_length=20, unique=True, verbose_name='用户账号'),
        ),
    ]
