# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-26 21:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AbstractUser', '0005_auto_20170121_2237'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.NullBooleanField(default=None, verbose_name='喜爱结果')),
            ],
        ),
        migrations.AddField(
            model_name='abstractuser',
            name='total_likes',
            field=models.IntegerField(default=0, verbose_name='喜爱总数'),
        ),
        migrations.AddField(
            model_name='likeuser',
            name='re_user_liked',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_liked', to='AbstractUser.AbstractUser', verbose_name='关联被喜爱用户'),
        ),
        migrations.AddField(
            model_name='likeuser',
            name='re_user_to_like',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_to_like', to='AbstractUser.AbstractUser', verbose_name='关联点评喜爱用户'),
        ),
    ]
