# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AbstractUser', '0007_abstractuser_introduce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractuser',
            name='introduce',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='一句话介绍'),
        ),
    ]
