# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-03 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AbstractUser', '0008_auto_20170602_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractuser',
            name='user_id',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='身份表的用户编号'),
        ),
        migrations.AddField(
            model_name='abstractuser',
            name='user_type',
            field=models.IntegerField(choices=[(0, '作者'), (1, '审稿')], default=0, verbose_name='用户身份'),
        ),
    ]
