# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-12 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Writer', '0001_initial'),
        ('Reviewer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer_name', models.CharField(default=None, max_length=10, verbose_name='笔名')),
                ('work_name', models.CharField(default=None, max_length=20, verbose_name='标题')),
                ('work_store', models.CharField(default=None, max_length=32, verbose_name='存储路径')),
                ('work_type', models.SmallIntegerField(default=(0,), verbose_name='作品类型')),
                ('is_public', models.BooleanField(default=True, verbose_name='是否公开')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否被删除')),
                ('status', models.SmallIntegerField(default=(0,), verbose_name='作品状态')),
                ('fee', models.FloatField(default=0, verbose_name='作品稿费')),
                ('re_reviewer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Reviewer.Reviewer', verbose_name='关联审稿')),
                ('re_writer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Writer.Writer', verbose_name='关联作者')),
            ],
        ),
    ]
