# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-02 14:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Work', '0004_auto_20170602_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='work_type',
        ),
        migrations.AddField(
            model_name='work',
            name='content',
            field=models.TextField(default=None, verbose_name='文章正文'),
        ),
        migrations.AddField(
            model_name='work',
            name='newest_version_work',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='newest_version', to='Work.Work', verbose_name='最新版本'),
        ),
        migrations.AlterField(
            model_name='work',
            name='last_version_work',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_version', to='Work.Work', verbose_name='上一版本的作品'),
        ),
    ]
