# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Work', '0005_auto_20170602_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='is_updated',
            field=models.BooleanField(default=False, verbose_name='是否有更新（此条无效）'),
        ),
    ]
