# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Work', '0006_work_is_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='work_name',
            field=models.CharField(db_index=True, default=None, max_length=20, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='work',
            name='writer_name',
            field=models.CharField(db_index=True, default=None, max_length=10, null=True, verbose_name='笔名'),
        ),
    ]
