# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-03 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Work', '0007_auto_20170602_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='total_visit',
            field=models.IntegerField(default=0, verbose_name='阅读人数'),
        ),
    ]
