# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-25 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Work', '0010_workgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='work_group_id',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='稿件组'),
        ),
    ]
