# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-14 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Writer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writer',
            name='total_works',
            field=models.IntegerField(default=0, verbose_name='全部作品数'),
        ),
    ]
