# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-15 12:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Writer', '0003_auto_20170602_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='followee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followee', to='AbstractUser.AbstractUser', verbose_name='关注者'),
        ),
    ]
