# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-12 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AbstractUser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('abstractuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='AbstractUser.AbstractUser')),
                ('rid', models.AutoField(auto_created=True, db_index=True, editable=False, primary_key=True, serialize=False, verbose_name='审稿员编号')),
                ('total_review', models.IntegerField(default=0, verbose_name='审稿总数')),
                ('total_received', models.IntegerField(default=0, verbose_name='审阅通过作品')),
                ('total_refused', models.IntegerField(default=0, verbose_name='审阅驳回作品')),
                ('total_upload', models.IntegerField(default=0, verbose_name='传稿总数')),
                ('privilege', models.SmallIntegerField(default=0, verbose_name='特权等级')),
            ],
            bases=('AbstractUser.abstractuser',),
        ),
    ]
