# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-13 22:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Work', '0001_initial'),
        ('Reviewer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_created=True, verbose_name='审稿时间')),
                ('content', models.CharField(default=None, max_length=500, verbose_name='评论')),
                ('result', models.BooleanField(default=(True,), verbose_name='审稿结果')),
                ('re_reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reviewer.Reviewer', verbose_name='关联审稿员')),
                ('re_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Work.Work', verbose_name='关联作品')),
            ],
        ),
    ]
