# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-14 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='create_time',
            new_name='comment_time',
        ),
        migrations.AddField(
            model_name='comment',
            name='is_updated',
            field=models.BooleanField(default=False, verbose_name='是否有更新（此条无效）'),
        ),
    ]
