# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-02 14:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Writer', '0003_auto_20170602_1401'),
        ('Work', '0004_auto_20170602_1401'),
        ('Comment', '0002_auto_20170114_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='WriterComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='创建时间')),
                ('content', models.CharField(default=None, max_length=500, verbose_name='评论')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否被删除')),
                ('re_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Work.Work', verbose_name='关联作品')),
                ('re_writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Writer.Writer', verbose_name='关联作者')),
            ],
        ),
        migrations.CreateModel(
            name='WriterLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='创建时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否被删除')),
                ('re_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Work.Work', verbose_name='关联作品')),
                ('re_writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Writer.Writer', verbose_name='关联作者')),
            ],
        ),
    ]
