# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comment', '0003_writercomment_writerlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_time',
            field=models.DateTimeField(auto_created=True, auto_now=True, verbose_name='审稿时间'),
        ),
    ]
