# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 23:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comment', '0004_auto_20170602_2110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='content_base64',
        ),
    ]
