# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comment', '0005_auto_20170602_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.CharField(default=None, max_length=500, verbose_name='评论（v2）'),
        ),
    ]
