# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-13 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comment', '0007_remove_comment_content_base64'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='评论（v2）'),
        ),
    ]
