# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-15 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Work', '0001_initial'),
        ('Writer', '0002_auto_20170114_1435'),
        ('Reviewer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='杂志标题')),
                ('create_time', models.DateTimeField(default=None, verbose_name='创建时间')),
                ('intro_words', models.CharField(default=None, max_length=300, verbose_name='本期作者介绍')),
                ('is_public', models.BooleanField(default=False, verbose_name='是否公开')),
                ('intro_writer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Writer.Writer', verbose_name='本期作者')),
                ('re_reviewer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Reviewer.Reviewer', verbose_name='关联审稿员')),
            ],
        ),
        migrations.CreateModel(
            name='MagazineWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='当前杂志的顺序')),
                ('re_magazine', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Magazine.Magazine', verbose_name='关联杂志')),
                ('re_work', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Work.Work', verbose_name='关联作品')),
            ],
        ),
    ]
